### ISSUE TITLE
Bonus from Gear Sets missing

### ISSUE THREAD

**Issue by odyright** [division2buildtool/division2buildtool.github.io#1]
`On your App`
![image](https://github.com/user-attachments/assets/ea8e098e-c8fe-4ace-856f-d8b9246cd04d)
CHC = 47

`In game`
![image](https://github.com/user-attachments/assets/b01b36ec-3fce-4ef5-ad2a-5ac069e04fca)
CHC = 56.5 => 9.5 + 5 + 5 + 6 + 6 + 15 + 10

**Comment by 269442033** [comment]
In the software you didn't select 9.5 CHC, it should be the wrong choice for the 3rd attribute of the weapon. the CHD is inconsistent because the software calculates the bonus of the negotiator suit 4-piece set (killing enemies increases CHD)

**Comment by odyright** [comment]
Hah ok i see, thank you for pointing me. Also, in Param, there are some parts still showing "Chinese".

**Comment by 269442033** [comment]
Since the software is basically used by Chinese, the English content was not checked. These basic words will  update translations in next release.

**Comment by odyright** [comment]
DO you accept private message?

**Comment by 269442033** [comment]
> DO you accept private message?

Email:269442033@qq.com
Steam Friend Codes:187499218
